.PHONY: clean All

All:
	@echo "----------Building project:[ second-assignment-system32 - Debug ]----------"
	@cd "second-assignment-system32" && "$(MAKE)" -f  "second-assignment-system32.mk"
clean:
	@echo "----------Cleaning project:[ second-assignment-system32 - Debug ]----------"
	@cd "second-assignment-system32" && "$(MAKE)" -f  "second-assignment-system32.mk" clean
